FROM node:16-alpine

#WORKDIR '/app'
USER node

RUN mkdir -p /home/node/app 
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
#COPY package.json .
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]